### PR TITLE
Global hotkeys

### PR DESCRIPTION
**Pull request by thomasboyt**

### CODE REVIEW

**Comment by thomasboyt** [comment]
tests for `<GlobalHotKeys>` would be good and also require some shuffling to make it testable, hm

**Comment by lazerwalker** [comment]
On master, I'm running into errors trying to add notes in the editor – at https://github.com/thomasboyt/bipp/blob/master/app/views/Editor/Handler.js#L183, "colMap" is a mapping of JS keyCodes -> column numbers (charCodes?), but the "key" variable contains a string representation of the key pressed from Mousetrap (e.g. "s"). As a result, the "col" property on the resulting note is undefined, which naturally causes all sorts of errors. (I also don't quite understand why the keys in colMap appear to be uppercase keys rather than lowercase, but that's a separate question). 

Before I spend too much time going down this rabbithole on my own, is the revamping of that code in this PR expected to fix those errors?

**Comment by thomasboyt** [comment]
whoops, looks like I wasn't paying attention during this commit and didn't notice that `colMap` inside `Editor/Handler.js` was different: https://github.com/thomasboyt/bipp/commit/f4301506d7558480f6237584906e685bf36db024

pushed a fix on master for that which should fix it

**Comment by lazerwalker** [comment]
:+1:

**Pull request merged**
